chore: Refactor branch deletion in cleanup-branch.yml

diff --git a/.github/workflows/04-terraform-apply-staging.yml b/.github/workflows/04-terraform-apply-staging.yml
--- a/.github/workflows/04-terraform-apply-staging.yml
+++ b/.github/workflows/04-terraform-apply-staging.yml
@@ -46,24 +46,39 @@ jobs:
           run: ${{ steps.apply-run.outputs.run_id }}
           comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
 
-  cleanup:
+  branch-cleanup:
     needs: [terraform-apply]
-    name: Cleanup Temporary Branch
-    if: needs.terraform-apply.result == 'success'
     runs-on: ubuntu-latest
     steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4.1.7
+        with:
+          fetch-depth: 0
+          token: ${{ secrets.PAT_TOKEN }}
+
       - name: Get Latest Release Version
         id: get_version
         run: |
           LATEST_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
           echo "LATEST_RELEASE=${LATEST_RELEASE}" >> $GITHUB_ENV
 
-      - name: Checkout Repository
-        uses: actions/checkout@v4.1.7
-
-      - name: Delete Temporary Branch
+      - name: Set and Delete Branch
+        id: set_and_delete_branch
         run: |
-          git push origin --delete release-${{ env.LATEST_RELEASE }}
+          BRANCH_NAME="release-${LATEST_RELEASE}"
+          echo "Attempting to delete branch: ${BRANCH_NAME}"
+          git push origin --delete ${BRANCH_NAME} || echo "Branch ${BRANCH_NAME} does not exist or couldn't be deleted"
+        env:
+          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
+
+      - name: Confirm deletion
+        run: |
+          if git ls-remote --exit-code --heads origin release-${LATEST_RELEASE}; then
+            echo "Branch release-${LATEST_RELEASE} still exists. Deletion failed."
+            exit 1
+          else
+            echo "Branch release-${LATEST_RELEASE} has been successfully deleted."
+          fi
 
   send-notification:
     needs: [terraform-apply]
