chore: Update Terraform workflow to determine version and generate hash

diff --git a/.github/workflows/04-terraform-apply-staging.yml b/.github/workflows/04-terraform-apply-staging.yml
--- a/.github/workflows/04-terraform-apply-staging.yml
+++ b/.github/workflows/04-terraform-apply-staging.yml
@@ -59,8 +59,19 @@ jobs:
       - name: Get Latest Release Version
         id: get_version
         run: |
-          LATEST_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
+          RESPONSE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
+          echo "API Response: $RESPONSE"
+          if [ "$(echo $RESPONSE | jq -r '.message')" = "Not Found" ]; then
+            echo "No releases found. Exiting."
+            exit 1
+          fi
+          LATEST_RELEASE=$(echo $RESPONSE | jq -r .tag_name)
+          if [ -z "$LATEST_RELEASE" ] || [ "$LATEST_RELEASE" = "null" ]; then
+            echo "Failed to get latest release version. Exiting."
+            exit 1
+          fi
           echo "LATEST_RELEASE=${LATEST_RELEASE}" >> $GITHUB_ENV
+          echo "Latest release version: $LATEST_RELEASE"
 
       - name: Set and Delete Branch
         id: set_and_delete_branch
